- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - manila-tempest-plugin-dummy-no-dhss
        - manila-tempest-plugin-dummy-dhss
        - manila-tempest-plugin-lvm
        - manila-tempest-plugin-zfsonlinux:
            voting: false
        - manila-tempest-plugin-cephfs-native:
            voting: false
        - manila-tempest-plugin-cephfs-nfs:
            voting: false
        - manila-tempest-plugin-container:
            voting: false
        - manila-tempest-plugin-generic:
            voting: false
    gate:
      queue: manila
      jobs:
        - manila-tempest-plugin-dummy-no-dhss
        - manila-tempest-plugin-dummy-dhss
        - manila-tempest-plugin-lvm
    experimental:
      jobs:
        - manila-tempest-dsvm-glusterfs-nfs:
            voting: false
        - manila-tempest-dsvm-glusterfs-native:
            voting: false
        - manila-tempest-dsvm-glusterfs-nfs-heketi:
            voting: false
        - manila-tempest-dsvm-glusterfs-native-heketi:
            voting: false
